#!/sbin/sh
diff ipncl.h ../../../util1/net/osf
diff ipncl.mes ../../../util1/net/osf
diff ipncl_pkg.c ../../../util1/net/osf
diff ipncl_priv.h ../../../util1/net/osf
diff ipnsv.h ../../../util1/net/osf
diff ipnsv.mes ../../../util1/net/osf
diff ipnsv_pkg.c ../../../util1/net/osf
diff ipnsv_priv.h ../../../util1/net/osf
diff ipport.h ../../../util1/net/osf
diff ipport_priv.h ../../../util1/net/osf
diff nis.h ../../../util1/net/osf
diff nis.mes ../../../util1/net/osf
diff nis_pkg.c ../../../util1/net/osf
diff nis_priv.h ../../../util1/net/osf
