.title		ncl_status_messages
.ident		'1-000'
.facility	NCL,102/PREFIX=NCL_

.severity	success
SUCCESS		<Normal completion>

.severity	error
NOMEM		<Insufficient virtual memory>
BADPARAM	<Bad function parameter>
PORTFULL	<Port contains maximum number of messages>
PORTEMPTY	<Port contains no messages>
NOTCON		<Port is not connected>
MBXFULL		<Mail box contains maximum number of messages>
NOEF		<Insufficient system resources>
TIMEOUT		<I/O read timeout>
