.title		nsv_status_messages
.ident		'1-000'
.facility	NSV,103/PREFIX=NSV_

.severity	success
SUCCESS		<Normal completion>

.severity	error
NOMEM		<Insufficient virtual memory>
BADPARAM	<Bad function parameter>
SHUTDOWN	<System shutdown message received>
PORTFULL	<Port contains maximum number of messages>
PORTEMPTY	<Port contains no messages>
NOTCON		<Port is not connected>
NOEF		<Insufficient system resources>
ABORT		<Connection aborted>
