.title          psgraph_status_messages
.ident          '1-000'
.facility       PSGRAPH,118/PREFIX=PSGRAPH_

.severity       success
SUCCESS         <Normal completion>

.severity       error
NO_DISPLAY	<Cannot open display>
NO_MEM		<Insufficient virtual memory>
NO_COLOR	<Cannot allocate color table entry>
NO_FONT		<Cannot load font>
BAD_OBJ		<Invalid object id>
SCALE_MISMATCH	<Invalid operation for scale type>
BAD_LOG_VALUE	<Value is <= 0, log is invalid>
